---------------
-- BASE QUERIES
---------------

SELECT * FROM SF_CASE
WHERE TRUNC(CREATEDDATE) >= TRUNC(SYSDATE)-90
AND ROWNUM <= 50000
ORDER BY CREATEDDATE DESC

SELECT * FROM SF_TASK
WHERE TRUNC(CREATEDDATE) >= TRUNC(SYSDATE)-90
AND ROWNUM <= 50000
ORDER BY CREATEDDATE DESC


----------------
-- A BASIC PIVOT
----------------

SELECT * FROM
(
    SELECT 
    CE_CASE_MGMT.SF_CASE.STATUS, 
    CE_CASE_MGMT.SF_CASE.ORIGIN, 
    CE_CASE_MGMT.SF_CASE.BRAND
    FROM CE_CASE_MGMT.SF_CASE
    WHERE TRUNC(CREATEDDATE) >= TRUNC(SYSDATE)-90 
    AND ROWNUM <= 50000
    AND STATUS = 'Open'
    ORDER BY CREATEDDATE DESC
)
pivot 
(
    count(STATUS)
    for BRAND in ('KOODO', 'TELUS')
);
